version: "3.7"
services:
  backend:
    build: .
    environment:
      - PORT=80
      - BASE_URL
    ports:
      - "${BACKEND_PORT}:80"
    volumes:
      - images:/data/images
    secrets:
      - session-key
      - google-keys
    depends_on:
      - mongodb
      - transformer
    networks:
      - board-camera
  mongodb:
    image: mongo
    volumes:
      - db:/data/db
    restart: on-failure
    networks:
      - board-camera
  transformer:
    build: transformer
    restart: on-failure
    networks:
      - board-camera
secrets:
  session-key:
    file: session-key
  google-keys:
    file: google-keys.json
volumes:
  db:
  images:
networks:
  board-camera:
