services:
  backend:
    labels:
      - traefik.http.routers.board-camera.rule=Host(`${TRAEFIK_HOST}`)
      - traefik.http.routers.board-camera.entrypoints=http
      - traefik.http.routers.board-camera.middlewares=redirect
      - traefik.http.routers.board-camera.rule=Host(`${TRAEFIK_HOST}`)
      - traefik.http.routers.board-camera.entrypoints=https
      - traefik.http.routers.board-camera.tls=true
      - traefik.http.routers.board-camera.tls.certresolver=letsencrypt
      - traefik.http.services.backend.loadbalancer.server.port=80
      - traefik.http.middlewares.redirect.redirectscheme.scheme=https
