version: "3.7"
services:
  backend:
    build: backend
    environment:
      - PORT=80
      - BASE_URL
    ports:
      - "${BACKEND_PORT}:80"
    volumes:
      - board-camera-images:/data/images
    secrets:
      - session-key
      - google-keys
    depends_on:
      - mongodb
      - transformer
  mongodb:
    image: mongo
    volumes:
      - board-camera-db:/data/db
  transformer:
    build: transformer
secrets:
  session-key:
    file: session-key
  google-keys:
    file: google-keys.json
volumes:
  board-camera-db:
  board-camera-images:
