services:
  backend:
    labels:
      - traefik.enable=true
      - traefik.http.routers.board-camera-http.rule=Host(`${TRAEFIK_HOST}`)
      - traefik.http.routers.board-camera-http.entrypoints=http
      - traefik.http.routers.board-camera-http.middlewares=redirect
      - traefik.http.routers.board-camera-https.rule=Host(`${TRAEFIK_HOST}`)
      - traefik.http.routers.board-camera-https.entrypoints=https
      - traefik.http.routers.board-camera-https.tls=true
      - traefik.http.routers.board-camera-https.tls.certresolver=letsencrypt
      - traefik.http.services.backend.loadbalancer.server.port=${BACKEND_PORT}
      - traefik.http.middlewares.redirect.redirectscheme.scheme=https
