env:
  node: true
extends:
  - airbnb-base
  - airbnb-typescript/base
parserOptions:
  project: ./tsconfig.json
rules:
  no-underscore-dangle:
    - error
    - allow: [ _id ]
  max-len: error
  import/prefer-default-export: off

